Class method to animate
KaiqueDamato/KDLoadingView pull request #5
Opened 2017-03-02 03:24 UTC by rodrigosoldi

Animate just using KDLoadingView.animate() in topView.
And just KDLoadingView.stop() to stop the animation

2017-07-13 17:48 UTC, KaiqueDamato requested changes
Please, update the example project with an example of what have been made.

2017-07-13 17:48 UTC, KaiqueDamato commented on KDLoadingView/KDLoadingBlurView.swift
> +class KDLoadingBlurView: UIVisualEffectView {
Make class public.

2017-07-13 17:48 UTC, KaiqueDamato commented on KDLoadingView/KDLoadingExtension.swift
> +        // Blur View
Delete the comment

2017-07-13 17:48 UTC, KaiqueDamato commented on KDLoadingView/KDLoadingExtension.swift
> +        guard let window = UIApplication.shared.keyWindow,
Maybe it's better to split the guard let and put some log explaining the problem in the else statement.

2017-07-13 17:48 UTC, KaiqueDamato commented on KDLoadingView/KDLoadingExtension.swift
> +        if let window = UIApplication.shared.keyWindow {
Maybe it's better to replace if let for guard let and put some log explaining the problem in else statement

2017-07-13 17:48 UTC, KaiqueDamato commented on KDLoadingView/KDLoadingExtension.swift
> +                return
Put some log explaining the problem in else statement

2017-07-13 17:48 UTC, KaiqueDamato commented on KDLoadingView/KDLoadingExtension.swift
> +                if view.isKind(of: KDLoadingBlurView.self) {
Try to replace the if for an if let with the cast

2017-07-13 17:48 UTC, KaiqueDamato commented on KDLoadingView/KDLoadingView.swift
> +
Remove the space

2017-08-09 22:43 UTC, rodrigosoldi reviewed
All the requests was fixed.

2018-10-11 19:38 UTC, merged